# Generated by Django 3.2.6 on 2021-08-14 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('bought', 'Bought'), ('left', 'Left'), ('not available', 'Not Available')], default='green', max_length=20)),
                ('date_created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
