# Generated by Django 3.2.6 on 2021-08-14 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_created',
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
