# Generated by Django 3.2.6 on 2021-08-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_auto_20210814_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='item_quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='item_status',
        ),
    ]
